name: speed_share
description: 局域网共享文件客户终端.
publish_to: "none"

version: 2.2.7+67

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 这是一个非开源库，需要编译该项目请移除改依赖和相关的代码
  speed_share_extension:
    path: ../speed_share_extension
  android_window: ^0.2.0
  tray_manager: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  window_manager: ^0.3.0
  animations: ^2.0.2
  desktop_drop: ^0.4.1
  # 分段下载，后面可能还需要弄一下
  # dio_range_download: ^1.0.1
  flutter_markdown: ^0.6.10+2
  clipboard_watcher: ^0.1.2
  signale: ^0.0.7
  file_manager_view:
    git: https://github.com/nightmare-space/file_manager_view.git
  file_selector: ^0.9.2+2
  get: ^4.1.3
  # 公共库
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  #动画组件
  simple_animations: ^5.0.0+3
  # 二维码生成
  qr_flutter: ^4.0.0
  open_file: ^3.2.1
  # scan qr code
  mobile_scanner: ^3.5.6
  # 文件部署
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  shelf_proxy: ^1.0.0
  shelf_static:
    git:
      url: https://github.com/nightmare-space/shelf
      path: pkgs/shelf_static
  # video preview
  better_player: ^0.0.83
  # 聊天服务器
  get_server: ^1.1.0
  # 安卓端文件选择
  file_picker: ^3.0.1
  # svg 图片展示
  flutter_svg: ^0.22.0
  # 跳转网页
  url_launcher: ^6.0.4
  # 压缩插件
  archive: ^3.1.2
  path: ^1.8.0
  # 获取文件对应的 mime_type 用的库
  mime_type: ^1.0.0
  # 网络请求
  dio: ^4.0.0
  # 响应式布局
  responsive_framework: ^1.0.0
  # 局域网设备发现
  multicast:
    git: https://github.com/nightmare-space/multicast
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  image_picker: ^0.8.5
  settings:
    git: https://github.com/nightmare-space/settings
  path_provider: ^2.0.10
  device_info_plus: 8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  # fonts:
  #   - family: MiSans
  #     fonts:
  #       - asset: assets/fonts/MiSans-Medium.ttf
  #       - asset: assets/fonts/MiSans-Bold.ttf
  #         weight: 700
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - CHANGELOG.md

dependency_overrides:
  flutter_svg: ^1.1.0
  # file_manager_view 依赖的是pub的shelf_static，速享需要使用自定义的
  shelf_static:
    git:
      url: https://github.com/nightmare-space/shelf
      path: pkgs/shelf_static
  ffi: 2.0.1
  android_intent_plus: ^4.0.3
  image_picker: ^1.0.4
  flutter_widget_from_html_core: ^0.14.6
flutter_intl:
  enabled: true
